install:
	cp -af applications/luci-app-zerotier/luasrc/* /usr/lib/lua/
	cp -af applications/luci-app-zerotier/root/* /
	cp -af applications/luci-app-zerotier/htdocs/* /www/

uninstall:
	echo TODO
	false

disable-code-cache:
	uci set luci.ccache.enable=0
	uci commit luci

enable-code-cache:
	uci set luci.ccache.enable=1
	uci commit luci
